services:
    application:
        build: .
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.train_api.entrypoints=web,websecure"
            - "traefik.http.routers.train_api.rule=Host(`train.reinaldyrafli.com`)"
            - "traefik.http.routers.train_api.tls.certresolver=tlsresolver"
            - "traefik.http.routers.train_api.middlewares=train_api-header,train_api-rate,train_api-redirectscheme"
            - "traefik.http.services.train_api.loadbalancer.server.port=5000"
            - "traefik.http.services.train_api.loadbalancer.server.scheme=http"
            - "traefik.http.services.train_api.loadbalancer.healthcheck.interval=30s"
            - "traefik.http.services.train_api.loadbalancer.healthcheck.path=/"
            - "traefik.http.middlewares.train_api-rate.ratelimit.average=100"
            - "traefik.http.middlewares.train_api-rate.ratelimit.burst=20"
            - "traefik.http.middlewares.train_api-rate.ratelimit.period=1s"
            - "traefik.http.middlewares.train_api-header.headers.addvaryheader=true"
            - "traefik.http.middlewares.train_api-header.headers.frameDeny=true"
            - "traefik.http.middlewares.train_api-header.headers.browserxssfilter=true"
            - "traefik.http.middlewares.train_api-header.headers.stsSeconds=604800"
            - "traefik.http.middlewares.train_api-header.headers.stsIncludeSubdomains=true"
            - "traefik.http.middlewares.train_api-header.headers.browserXssFilter=true"
            - "traefik.http.middlewares.train_api-header.headers.contentTypeNosniff=true"
            - "traefik.http.middlewares.train_api-header.headers.customResponseHeaders.server=Reinaldy Rafli"
            - "traefik.http.middlewares.train_api-redirectscheme.redirectscheme.scheme=https"
            - "traefik.http.middlewares.train_api-redirectscheme.redirectscheme.permanent=true"
        platform: linux/amd64
        healthcheck:
            test: curl -f http://localhost:5000 || exit 1
            interval: 15s
            timeout: 10s
            retries: 5
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 30s
                max_attempts: 10
                window: 120s
            resources:
                limits:
                    memory: 500MB
                    cpus: '1'
                reservations:
                    memory: 25MB
                    cpus: '0.10'
        networks:
            - train_api
        logging:
            driver: json-file
            options:
                max-size: 10M
                max-file: 3

networks:
    train_api:
        external: true
        driver: bridge